<?php
/**
 * @file    twit
 * @author  ryan <cumt.xiaochi@gmail.com>
 * @created Jul 17, 2012 4:38:13 PM
 */
?>
<div class="twit">
  <div class="comment">
    <?php if (count($this->comments) == 0) { ?>
    <div>还没有评论，沙发空着呢</div>
    <?php } else { ?>
    <ul class="comment">
    <?php foreach ($this->comments as $c) { ?>
      <li class="comment">
        <a href="<?php echo '/role/'.$c->role_id; ?>">
          <img src="<?php echo $c->avatar ?>" />
          <span><?php echo $c->author; ?></span>
        </a>
        <span>：<?php echo $c->text; ?></span>
      </li>
    <?php } ?>
    </ul>
    <?php } ?>
  </div>
</div>

