<?php
/**
 * @file    twit
 * @author  ryan <cumt.xiaochi@gmail.com>
 * @created Jul 27, 2012 5:29:06 PM
 * need $t as $twit
 */
?>
<li class="twit" data-id="<?php echo $this->twit->id; ?>" id="t<?php echo $this->twit->id ?>">

  <div class="left-col">
    <a href="<?php echo '/role/'.$this->role->id; ?>">
      <img class="img-thumbnail" title="" src="<?php echo $this->role->avatar; ?>" />
    </a>
  </div>

  <div class="right-col clearfix">

    <div class="name-bar">
      <a href="<?php echo '/role/'.$this->role->id; ?>" class="name"><?php echo $this->role->name; ?></a>
      <span class="time label label-info pull-right"><?php echo $this->twit->created; ?></span>
    </div>
    
    <div class="content">
      <span class="text"><?php echo $this->twit->text; ?></span>
    </div>

    <?php if (0 || $this->twit->origin): ?>
    <div class="box-bg">
      <div class="origin row-fluid">
        <div class="avatar span1">
          <a href="<?php echo '/role/'.$this->twit->origin['role_id']; ?>">
            <img src="<?php echo $this->twit->origin['avatar']?:$config['default_avatar']; ?>" class="img-polaroid" />
          </a>
        </div>
        <div class="span11">
          <span class="time label pull-right"><?php echo $this->twit->origin['time']; ?></span>
          <a href="<?php echo '/role/'.$this->twit->origin['role_id']; ?>">
            <?php echo $this->twit->origin['author']; ?>
          </a>
          <?php if ($this->twit->origin['is_v']): ?>
            <span class="verify">V</span>
          <?php endif ?>
          <span class="text"><?php echo $this->twit->origin['text']; ?></span>
        </div>
        <?php if ($this->twit->origin['image']): ?>
          <div class="image row">
            <img src="<?php echo $this->twit->origin['image']; ?>" class="img-polaroid" />
          </div>
        <?php endif ?>
        <div class="control">
            <span class="">转发(<?php echo $this->twit->origin['retweet_num']; ?>)</span>
            <?php if (0) { ?><a class="">评论（<?php echo $this->twit->origin['comment_num']; ?>）</a><?php } ?>
        </div>
      </div>
    </div>
    <?php endif ?>

    <div class="control pull-right">
      <button type="button" class="btn btn-default">转发</button>
      <button type="button" class="btn btn-default">评论</button>
    </div>

    <?php if ($this->role->id || $this->comments): ?>
      <?php $this->renderBlock('twit/comments'); ?>
    <?php endif ?>

    <div class="retweet box-bg" style="display: none">
      <div class="row-fluid">
        <form class="retweet" method="post" action="<?php echo '/twit/'.$this->twit->id; ?>">
          <div class="span1">
            <img class="img-polaroid" src="<?php echo $this->twit->avatar; ?>" />
          </div>
          <div class="span11">
            <textarea name="text" placeholder="说点什么吧" class="span12"></textarea>
          </div>
          <input type="hidden" name="method" value="retweet" />
          <div class="row">
            <input type="submit" value="转发" class="btn pull-right" />
          </div>
        </form>
      </div>
    </div>
  </div>
</li>
