<?php

/**
 * @file    header
 * @author  ryan <cumt.xiaochi@gmail.com>
 * @created Jun 30, 2012 11:27:00 AM
 */
?>
<div class="control pull-right">
<?php if ($this->role): ?>
  <span>正在扮演</span>
  <a href="<?php echo '/role/'.$this->role->id; ?>">
    <img src="<?php echo $this->role->avatar; ?>" />
    <span class="name"><?php echo $this->role->name; ?></span>
  </a>
  <a href="/role/">角色列表</a>
<?php else: ?>
  <a href="/role/">扮演角色</a>
<?php endif ?>
</div>

<h1 title="伪博扮演 首页">
  <a href="/">
    <span class="text">伪博扮演</span>
  </a>
</h1>
