<?php
/**
 * @author  ryan <cumt.xiaochi@gmail.com>
 */
?>
<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <title>伪博扮演</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="/css/style.css">

  </head>
  <body>
    <div class="header"><!-- head -->
      <?php $this->renderBlock('block/header'); ?>
    </div>
    <div class="page-content clearfix">
      <?php $this->yieldView(); ?>
    </div>

    <?php if (DEPLOY_ENV == 'prd'): ?>
    <script type="text/javascript">
    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-34837342-1']);
    _gaq.push(['_trackPageview']);

    (function() {
      var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
      ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();
    </script>
    <?php endif; ?>

  </body>
</html>
