<?php
/**
 * @file    index
 * @author  ryan <cumt.xiaochi@gmail.com>
 * @created Jul 17, 2012 9:51:11 AM
 */
?>
<div class="index">
  <?php if ($this->role) { ?>
  <div class="image-holder well"></div>
  <div class="row-fluid">
    <div class="span1">
      <img class="img-polaroid" src="<?php echo $role_info['avatar'] ?>">
    </div>
    <div class="span11">
      <form action="twit" method="post" enctype="multipart/form-data">
        <input type="hidden" name="scene" value="<?php echo $scene_id; ?>" />
        <input type="hidden" name="method" value="post" />
        <div class="post-form clear-fix">
          <textarea class="span12" name="text" placeholder="有什么需要表演的？"></textarea>
          <input type="submit" class="btn btn-primary pull-right" value="发布" />
          <div>
            <label for="fileInput" class="btn"><i class="icon-picture"></i>图片</label>
            <input type="hidden" name="image_src" >
          </div>
        </div>
      </form>
      <input type="file" id="fileInput" name="image" data-url="/twit_pre_upload" />
    </div>
  </div>
  <?php } else { ?>
  <div class="choose">请首先<a href="<?php echo ROOT; ?>role">选择一个角色</a>，开始在伪博扮演的旅程吧</div>
  <?php } ?>
  <div class="scene-twit row-fluid">
      <ul class="twit span10">
      <?php foreach ($this->twits as $t) { ?>
        <?php include $this->renderView('twit/twit'); ?>
      <?php } ?>
      </ul>
  </div>
  <div class="paginate">
    <?php if ($this->paginate->hasPrevious()) { ?><a href="<?php echo ROOT.'?offset='.$this->paginate->previousOffset(); ?>">上一页</a><?php } ?>
    <?php if ($this->paginate->hasNext()) { ?><a href="<?php echo ROOT.'?offset='.$this->paginate->nextOffset(); ?>">下一页</a><?php } ?>
  </div>
</div>


