<?php
/**
 * @file    index
 * @author  ryan <cumt.xiaochi@gmail.com>
 * @created Jul 17, 2012 9:51:11 AM
 */
?>
<div class="index">
  <?php if ($this->role): ?>
  <div class="post-box col-md-10 col-md-offset-1">
    <div class="left-col">
      <img class="img-thumbnail" src="<?php echo $this->role->avatar ?>">
    </div>
    <div class="right-col">
      <form action="/twit/" method="post">
        <input type="submit" class="btn btn-primary" value="发布" />
        <div class="mid-col">
          <textarea class="form-control" name="text" placeholder="有什么需要表演的？"></textarea>
        </div>
      </form>
    </div>
  </div>
  <?php else: ?>
  <div class="choose">请首先<a href="/role/">选择一个角色</a>，开始在伪博扮演的旅程吧</div>
  <?php endif; ?>
  <div class="twit-list-div">
    <ul class="twit-list-ul col-md-10 col-md-offset-1 list-unstyled">
    <?php foreach ($this->twits as $t) { ?>
      <?php $this->renderBlock('twit/twit', array('twit' => $t, 'role' => $t->getRole(), 'comments' => $t->getComments())); ?>
    <?php } ?>
    </ul>
  </div>
  <div class="paginate">
    <?php if ($this->paginate->hasPrevious()) { ?><a href="<?php echo '?offset='.$this->paginate->previousOffset(); ?>">上一页</a><?php } ?>
    <?php if ($this->paginate->hasNext()) { ?><a href="<?php echo '?offset='.$this->paginate->nextOffset(); ?>">下一页</a><?php } ?>
  </div>
</div>
